// autogenerated by scripts/create-i18n.js
import { getMessage as getMessageGlobal } from '@hint/utils-i18n';
export type MessageName =
    'elementsWithStyleAttributeFound' |
    'description' |
    'styleElementFound' |
    'name';
export const getMessage = (message: MessageName, language: string, substitutions?: string | string[]) => {
    const options = {
        language,
        substitutions
    };

    return getMessageGlobal(message, __dirname, options);
};
